import type { Metadata, Viewport } from "next";
import { Manrope, Inter } from "next/font/google";
import { SITE_URL, brand } from "@/data/site";
import { jsonLdGraph, localBusinessSchema, organizationSchema, websiteSchema } from "@/lib/schema";
import { JsonLd } from "@/components/seo/JsonLd";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { MobileCtaBar } from "@/components/layout/MobileCtaBar";
import { DevSetupBanner } from "@/components/layout/DevSetupBanner";
import "./globals.css";

/* Self-hosted at build time by next/font - no request ever leaves for a font. */
const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-manrope",
  weight: ["500", "600", "700", "800"],
});

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: `${brand.name} | ${brand.tagline}`,
    template: `%s | ${brand.name}`,
  },
  description: brand.description,
  applicationName: brand.name,
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
  formatDetection: { telephone: false },

  /* Real files with real extensions, generated by scripts/generate-icons.mjs.
     Next's file-based icon conventions emit extension-less routes under
     `output: "export"`, which static hosts serve with the wrong Content-Type. */
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
      { url: "/favicon.ico", sizes: "16x16 32x32 48x48" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180" }],
  },
  manifest: "/site.webmanifest",
};

export const viewport: Viewport = {
  themeColor: "#122d3b",
  colorScheme: "light",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const structuredData = jsonLdGraph(
    organizationSchema(),
    websiteSchema(),
    localBusinessSchema(),
  );

  return (
    <html lang="en" className={`${manrope.variable} ${inter.variable}`}>
      <body className="min-h-screen">
        {/* Scroll-reveal hides content until it animates in. If scripting is
            off that never happens, so restore it here. <noscript> is inert
            when JS runs, which keeps this out of the hydration path entirely
            - no class juggling on <html>, no server/client mismatch. */}
        <noscript>
          <style>{`.reveal{opacity:1!important;transform:none!important}`}</style>
        </noscript>

        <a
          href="#main-content"
          className="sr-only rounded-lg bg-navy px-4 py-2 font-display text-sm font-semibold text-white focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-[60]"
        >
          Skip to content
        </a>

        <DevSetupBanner />
        <Header />

        <main id="main-content">{children}</main>

        <Footer />

        {/* Reserves the height of the fixed mobile bar so it never overlaps
            the end of the footer. */}
        <div aria-hidden="true" className="h-[4.75rem] lg:hidden" />
        <MobileCtaBar />

        <JsonLd data={structuredData} />
      </body>
    </html>
  );
}
